#!/usr/bin/env bash
# Script to run ROVIOLI from a Euroc rosbag data source.
# Usage: tutorial_euroc <output save folder> <rosbag path> [<additional rovioli flags>]

NCAMERA_CALIBRATION="$ROVIO_CONFIG_DIR/ncamera_cla.yaml"
IMU_PARAMETERS_MAPLAB="$ROVIO_CONFIG_DIR/imu-adis16488_cla.yaml"
IMU_PARAMETERS_ROVIO="$ROVIO_CONFIG_DIR/imu-sigmas-rovio_cla.yaml"
REST=$@

rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --log_dir=/persist/data/cla_floor_f_brisk_freak_test/log/brisk_log \
  --v=1 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --imu_parameters_rovio=$IMU_PARAMETERS_ROVIO \
  --datasource_type="rosbag" \
  --save_map_folder="/persist/data/cla_floor_f_brisk_freak_test/cla_floor_f_brisk" \
  --optimize_map_to_localization_map=false \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=/persist/data/cla_floor_f.bag 


rosrun rovioli rovioli \
  --alsologtostderr=1 \
  --log_dir=/persist/data/cla_floor_f_brisk_freak_test/log/freak_log \
  --v=1 \
  --ncamera_calibration=$NCAMERA_CALIBRATION  \
  --imu_parameters_maplab=$IMU_PARAMETERS_MAPLAB \
  --imu_parameters_rovio=$IMU_PARAMETERS_ROVIO \
  --datasource_type="rosbag" \
  --save_map_folder="/persist/data/cla_floor_f_brisk_freak_test/cla_floor_f_freak" \
  --optimize_map_to_localization_map=false \
  --map_builder_save_image_as_resources=false \
  --datasource_rosbag=/persist/data/cla_floor_f.bag \
  --swe_feature_tracking_descriptor_type=freak \top
  --feature_descriptor_type=freak 
